# Generated by Django 2.2.5 on 2019-12-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cvs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('topic', models.IntegerField()),
                ('article_time', models.TextField()),
                ('article_link', models.TextField()),
                ('message', models.IntegerField()),
                ('push_count', models.IntegerField()),
                ('push_message', models.TextField()),
                ('bull_count', models.IntegerField()),
                ('bull_message', models.TextField()),
                ('arrow_count', models.IntegerField()),
                ('arrow_message', models.TextField()),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
